# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: carlosprojects
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-nodejs
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-nodejs

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    DEBUG: ${env:DEBUG, 0} 
    STAGE: ${env:STAGE, "prod"}
  iam:
    role:
      name: serverless-ssm-role-${env:STAGE, "prod"}
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:GetParameterByPath"
            - "ssm:GetParameterHistory"
            - "ssm:DescribeParameters"

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

custom: 
  dotenv:
    exclude:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - DATABASE_URL

plugins:
  - serverless-offline
  - serverless-dotenv-plugin